source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘9.0’
use_frameworks!
target ‘Barbershop’ do
	pod 'Cosmos', '~> 9.0'
	pod 'IGListKit', '~> 3.0’
	pod 'FSCalendar'
	pod ‘Toast-Swift’, ‘~> 2.0.0’
	pod ‘Firebase/Core’
	pod ‘Firebase/Database’
	pod ‘Firebase/Auth’
	pod ‘Firebase/Storage’
	pod 'Fabric'
	pod 'Crashlytics'
  	pod 'Kingfisher', '~> 3.0'
	pod 'JSQMessagesViewController'
	pod 'ViewDeck'
	pod ‘Stripe’
	pod ‘GoogleSignIn’
	pod 'FacebookCore'
	pod 'FacebookLogin'
	pod 'FacebookShare’
	pod 'FBSDKCoreKit'
	pod 'FBSDKLoginKit'
	pod 'FBSDKShareKit'
	pod 'XLPagerTabStrip', '~> 7.0'

	target ‘BarbershopTests’ do
		pod 'Cosmos', '~> 9.0'
		pod 'IGListKit', '~> 3.0’
		pod 'FSCalendar'
		pod ‘Toast-Swift’, ‘~> 2.0.0’
		pod ‘Firebase/Core’
	end

end